// src/pages/Orders.jsx
import React, { useState, useEffect } from 'react';
import SearchBar from '../components/SearchBar';
import OrderList from '../components/OrderList';
import OrderDetails from '../components/OrderDetails';
import InvoiceList from '../components/InvoiceList';
import InvoiceDetails from '../components/InvoiceDetails';
import styles from '../styles/Orders.module.css';
import { jsPDF } from 'jspdf';

const Orders = () => {
    const [activeTab, setActiveTab] = useState('orders'); // 'orders' or 'invoices'
    const [searchTerm, setSearchTerm] = useState('');
    const [orders, setOrders] = useState([]);
    const [invoices, setInvoices] = useState([]);
    const [selectedOrder, setSelectedOrder] = useState(null);
    const [selectedInvoice, setSelectedInvoice] = useState(null);
    const [selectedInvoices, setSelectedInvoices] = useState([]); // For multi-select
    const [exporting, setExporting] = useState(false);

    // Simulate fetching orders from backend
    useEffect(() => {
        const sampleOrders = [
            { id: 1, orderNumber: 'ORD-001', items: ['Product A', 'Product B'], status: 'pending', total: 150.0 },
            { id: 2, orderNumber: 'ORD-002', items: ['Product C'], status: 'completed', total: 99.99 },
            { id: 3, orderNumber: 'ORD-003', items: ['Product D', 'Product E'], status: 'processing', total: 200.0 },
        ];
        setOrders(sampleOrders);
    }, []);

    // Simulate fetching invoices from backend (generated by admin)
    useEffect(() => {
        const sampleInvoices = [
            { id: 101, invoiceNumber: 'INV-001', orderDetails: 'Details for order ORD-001', total: 150.0 },
            { id: 102, invoiceNumber: 'INV-002', orderDetails: 'Details for order ORD-002', total: 99.99 },
        ];
        setInvoices(sampleInvoices);
    }, []);

    // Filter orders and invoices based on search term
    const filteredOrders = orders.filter(order =>
        order.orderNumber.toLowerCase().includes(searchTerm.toLowerCase())
    );
    const filteredInvoices = invoices.filter(invoice =>
        invoice.invoiceNumber.toLowerCase().includes(searchTerm.toLowerCase())
    );

    const handleOrderSelect = (order) => {
        setSelectedOrder(order);
    };

    const handleInvoiceSelect = (invoice) => {
        setSelectedInvoice(invoice);
    };

    // Toggle invoice selection for multi-export
    const toggleInvoiceSelection = (invoiceId) => {
        setSelectedInvoices(prev =>
            prev.includes(invoiceId)
                ? prev.filter(id => id !== invoiceId)
                : [...prev, invoiceId]
        );
    };

    // Cancel order only if its status is pending
    const cancelOrder = (orderId) => {
        if (window.confirm("Are you sure you want to cancel this order?")) {
            setOrders(prevOrders =>
                prevOrders.map(order =>
                    order.id === orderId ? { ...order, status: 'cancelled' } : order
                )
            );
            setSelectedOrder(null);
        }
    };

    // Improved exporting selected invoices as PDF using jsPDF
    // ... inside Orders.jsx, replace the exportInvoices function with the following:

    const exportInvoices = () => {
        if (selectedInvoices.length === 0) {
          alert('Please select at least one invoice to export.');
          return;
        }
      
        setExporting(true);
      
        // Filter the selected invoices details
        const invoicesToExport = invoices.filter(invoice => selectedInvoices.includes(invoice.id));
      
        // Create a new PDF document
        const doc = new jsPDF();
      
        // Define dimensions and positions
        const pageWidth = doc.internal.pageSize.getWidth();
        let yOffset = 20;
      
        // Header Section: Company Info & Title
        doc.setFontSize(18);
        doc.setTextColor(40);
        doc.text('Your Company Name', pageWidth / 2, yOffset, { align: 'center' });
        yOffset += 8;
        doc.setFontSize(10);
        doc.text('1234 Street Address, City, Country', pageWidth / 2, yOffset, { align: 'center' });
        yOffset += 10;
        doc.setFontSize(16);
        doc.text('Invoice', pageWidth / 2, yOffset, { align: 'center' });
        yOffset += 10;
      
        // Draw a horizontal line
        doc.setLineWidth(0.5);
        doc.line(20, yOffset, pageWidth - 20, yOffset);
        yOffset += 10;
      
        // Loop through each selected invoice
        invoicesToExport.forEach((invoice, index) => {
          // Save the top coordinate for the invoice rectangle
          const rectX = 20;
          const rectY = yOffset;
          const rectWidth = pageWidth - 40;
          const innerMargin = 5;
          let textY = rectY + innerMargin; // start text inside rectangle with margin
          const textX = rectX + innerMargin;
      
          doc.setFontSize(12);
          doc.setTextColor(0);
          doc.text(`Invoice Number: ${invoice.invoiceNumber}`, textX, textY);
          textY += 7;
          doc.text(`Order Details:`, textX, textY);
          textY += 7;
      
          // Wrap order details text if needed
          const detailsLines = doc.splitTextToSize(invoice.orderDetails, rectWidth - 2 * innerMargin);
          doc.text(detailsLines, textX, textY);
          textY += detailsLines.length * 7;
          doc.text(`Total Amount: $${invoice.total.toFixed(2)}`, textX, textY);
          textY += 7; // Final line spacing inside rectangle
      
          // Calculate rectangle height based on text content plus bottom margin
          const rectHeight = textY - rectY + innerMargin;
          doc.setLineWidth(0.3);
          doc.rect(rectX, rectY, rectWidth, rectHeight);
      
          // Update yOffset for next invoice with some spacing
          yOffset = rectY + rectHeight + 15;
      
          // If page is almost full, add a new page and redraw header if needed
          if (yOffset > 250 && index !== invoicesToExport.length - 1) {
            doc.addPage();
            yOffset = 20;
            // Redraw header elements on new page
            doc.setFontSize(18);
            doc.text('Your Company Name', pageWidth / 2, yOffset, { align: 'center' });
            yOffset += 8;
            doc.setFontSize(10);
            doc.text('1234 Street Address, City, Country', pageWidth / 2, yOffset, { align: 'center' });
            yOffset += 10;
            doc.setFontSize(16);
            doc.text('Invoice', pageWidth / 2, yOffset, { align: 'center' });
            yOffset += 10;
            doc.setLineWidth(0.5);
            doc.line(20, yOffset, pageWidth - 20, yOffset);
            yOffset += 10;
          }
        });
      
        // Save the PDF
        doc.save('invoices.pdf');
      
        // Reset selections and exporting state after export
        setExporting(false);
        setSelectedInvoices([]);
      };
      


    return (
        <div className={styles.ordersPage}>
            <div className={styles.tabButtons}>
                <button
                    className={activeTab === 'orders' ? styles.active : ''}
                    onClick={() => setActiveTab('orders')}
                >
                    Orders
                </button>
                <button
                    className={activeTab === 'invoices' ? styles.active : ''}
                    onClick={() => setActiveTab('invoices')}
                >
                    Invoices
                </button>
            </div>
            <SearchBar searchTerm={searchTerm} setSearchTerm={setSearchTerm} />
            <div className={styles.content}>
                {activeTab === 'orders' && (
                    <>
                        <div className={styles.listContainer}>
                            <OrderList orders={filteredOrders} onSelect={handleOrderSelect} />
                        </div>
                        <div className={styles.detailsContainer}>
                            {selectedOrder ? (
                                <OrderDetails order={selectedOrder} onCancel={cancelOrder} />
                            ) : (
                                <p>Select an order to view details</p>
                            )}
                        </div>
                    </>
                )}
                {activeTab === 'invoices' && (
                    <>
                        <div className={styles.listContainer}>
                            <InvoiceList
                                invoices={filteredInvoices}
                                selectedInvoices={selectedInvoices}
                                toggleInvoiceSelection={toggleInvoiceSelection}
                                onSelect={handleInvoiceSelect}
                            />
                        </div>
                        <div className={styles.detailsContainer}>
                            {selectedInvoice ? (
                                <InvoiceDetails
                                    invoice={selectedInvoice}
                                    onClose={() => setSelectedInvoice(null)}
                                />
                            ) : (
                                <p>Click an invoice to view details</p>
                            )}
                            {filteredInvoices.length > 0 && (
                                <button
                                    onClick={exportInvoices}
                                    className={styles.exportButton}
                                    disabled={exporting}
                                >
                                    {exporting ? 'Exporting...' : 'Export Selected as PDF'}
                                </button>
                            )}
                        </div>
                    </>
                )}
            </div>
        </div>
    );
};

export default Orders;
